// <auto-generated />
using System;
using GreenDriveApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenDriveApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("GreenDriveApi.Models.Bateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacidadeKWh")
                        .HasColumnType("REAL");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SaudeBateria")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Baterias");
                });

            modelBuilder.Entity("GreenDriveApi.Models.EstacaoCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CargaDisponivelKW")
                        .HasColumnType("REAL");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCarga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstacoesCarga");
                });

            modelBuilder.Entity("GreenDriveApi.Models.OrdemReciclagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CustoProcessamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BateriaId");

                    b.HasIndex("EstacaoId");

                    b.ToTable("OrdensReciclagem");
                });

            modelBuilder.Entity("GreenDriveApi.Models.RegistroTelemetria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperatura")
                        .HasColumnType("REAL");

                    b.Property<double>("Voltagem")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BateriaId");

                    b.ToTable("RegistrosTelemetria");
                });

            modelBuilder.Entity("GreenDriveApi.Models.OrdemReciclagem", b =>
                {
                    b.HasOne("GreenDriveApi.Models.Bateria", "Bateria")
                        .WithMany()
                        .HasForeignKey("BateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDriveApi.Models.EstacaoCarga", "Estacao")
                        .WithMany()
                        .HasForeignKey("EstacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bateria");

                    b.Navigation("Estacao");
                });

            modelBuilder.Entity("GreenDriveApi.Models.RegistroTelemetria", b =>
                {
                    b.HasOne("GreenDriveApi.Models.Bateria", "Bateria")
                        .WithMany()
                        .HasForeignKey("BateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bateria");
                });
#pragma warning restore 612, 618
        }
    }
}
